version: "3.7"
services:
    php:
        container_name: desafio_php
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: docker/php/Dockerfile
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network

    nginx:
        hostname: desafio.localhost
        image: nginx:alpine
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - app-network

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: desafio
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
